#!/usr/bin/env bash
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Author:   li.lei03@opg.cn
# Created:  2020-10-01
# Purpose:  Flume Controller at peer of DS dept
# Docs:     https://github.com/opgcn/dsflume-client

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# global configs

set -o pipefail

source $(dirname $(realpath ${BASH_SOURCE[0]}))/conf/flume-env.sh || exit $?

URL_DOCS="https://github.com/opgcn/dsflume-client"
SYSTEMD_UNIT_NAME=$(basename $FLUME_HOME)
FILE_THIS=$(basename ${BASH_SOURCE[0]})
IS_LOGGING=1
LIFECYCLE_SINK_DISCARDS=15d
LIFECYCLE_FLUME_LOGS=30d

TPL_UNIT="\
# This unit file is generated by $(realpath ${BASH_SOURCE[0]}) at $(date +"%F %T %z")

[Unit]
Description=${SYSTEMD_UNIT_NAME}
Documentation=${URL_DOCS}
After=local-fs.target remote-fs.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=${FLUME_HOME}
ExecStart=${FLUME_DIR_BIN}/flume-ng agent -n a -c conf -f ${FLUME_DIR_CONF}/default.conf
TimeoutSec=10

[Install]
WantedBy=multi-user.target\
"

TPL_SYSTEMCTL="\
# Display systemd startup logs
journalctl -u $SYSTEMD_UNIT_NAME

# Show runtime status
systemctl status -l $SYSTEMD_UNIT_NAME

# Start or restart $SYSTEMD_UNIT_NAME
systemctl restart $SYSTEMD_UNIT_NAME

# Stop $SYSTEMD_UNIT_NAME
systemctl stop $SYSTEMD_UNIT_NAME

# Enable auto-restart $SYSTEMD_UNIT_NAME when power on
systemctl enable $SYSTEMD_UNIT_NAME

# Disable auto-restart $SYSTEMD_UNIT_NAME when power on
systemctl disable $SYSTEMD_UNIT_NAME\
"

TPL_TEST='# Test with Netcat protocol, you can use:
nc -v localhost 20002 <<EOF
V2|$(hostname -I | cut -d" " -f1)|TEST_EXAMPLE_TYPE_1|TEST|$(date +"%F %T")|字段5|字段6|字段7
V2|$(hostname -I | cut -d" " -f1)|TEST_EXAMPLE_TYPE_2|TEST|$(date +"%F %T")|字段V|字段VI
EOF'

HELP="\
$FILE_THIS - Controller for '$SYSTEMD_UNIT_NAME'.

Usage:
    reinstall   Reinstall Apache Flume from Internet to $FLUME_HOME/
    unit        Update systemd unit file and reload it
                /usr/lib/systemd/system/$SYSTEMD_UNIT_NAME.service
    systemctl   Show systemctl commands controling '$SYSTEMD_UNIT_NAME' service
    du          Query disk usages:
                $FLUME_DIR_CHANNELS/
                $FLUME_DIR_SINKS/
                $FLUME_DIR_LOGS/
    verify      Verify all channels' datadirs
                $FLUME_DIR_CHANNELS/*/data/
    housekeep   Clean caches left over from history:
                $FLUME_DIR_LOGS/ with time threshold $LIFECYCLE_FLUME_LOGS
                $FLUME_DIR_SINKS/ with time threshold $LIFECYCLE_SINK_DISCARDS
                typically set in crontab:
                @daily bash -l $(realpath ${BASH_SOURCE[0]}) housekeep
    test        Display commands sending testing V2 messages to localhost
    help        Show this help message
    
$URL_DOCS\
"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# common functions

function echoDebug
# echo debug message
#   $1: debug level
#   $2: message string
{
    if [ 1 -eq ${IS_LOGGING} ]; then
        echo -e "\e[7;93m[$FILE_THIS $(date +'%F %T') $1]\e[0m \e[93m$2\e[0m" >&2
    fi
}

function runCmd
{
    echoDebug DEBUG "Running command: $*"
    "$@"
    nRet=$?; [ 0 -eq $nRet ] || echoDebug WARN "Fetch non-zero return code '$nRet' from cmd: $*"
    return $nRet
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# process functions

function main
{
    declare sOpt="$1"
    if [ "$sOpt" == "help" ] || [ "$sOpt" == '' ]; then
        echo "$HELP"
    elif [ "$sOpt" == "reinstall" ]; then
        choDebug INFO "Installing Apache Flume to $FLUME_HOME"
        sDirTmp=$FLUME_HOME/tmp.d
        sUrlDownload='https://mirrors.tuna.tsinghua.edu.cn/apache/flume/1.9.0/apache-flume-1.9.0-bin.tar.gz'
        sPathTargz=$sDirTmp/$(basename $sUrlDownload)
        sDirExtracted=$sDirTmp/$(basename $sPathTargz .tar.gz)
        runCmd rm -rf $sDirTmp \
        && runCmd mkdir -p $sDirTmp \
        && runCmd wget $sUrlDownload -O $sPathTargz \
        && runCmd tar -C $sDirTmp -xzf $sPathTargz \
        && runCmd mkdir -p $FLUME_DIR_PLUGINS $FLUME_DIR_CHANNELS $FLUME_DIR_SINKS $FLUME_DIR_LOGS \
        && runCmd rm -rf $FLUME_DIR_BIN $FLUME_DIR_LIB $FLUME_DIR_TOOLS \
        && runCmd mv $sDirExtracted/bin $sDirExtracted/lib $sDirExtracted/tools $FLUME_HOME \
        && runCmd mv -f $sDirExtracted/conf/log4j.properties $FLUME_DIR_CONF \
        && runCmd rm -rf $sDirTmp \
        && runCmd ls -alFh --time-style=long-iso --color=auto $FLUME_HOME
    elif [ "$sOpt" == "unit" ]; then
        echoDebug INFO "Installing systemd unit file of '$SYSTEMD_UNIT_NAME'" \
        && echo "$TPL_UNIT" > /usr/lib/systemd/system/$SYSTEMD_UNIT_NAME.service \
        && runCmd cat /usr/lib/systemd/system/$SYSTEMD_UNIT_NAME.service \
        && runCmd exec systemctl daemon-reload
    elif [ "$sOpt" == "systemctl" ]; then
        echoDebug INFO "Show systemctl commands controling '$SYSTEMD_UNIT_NAME' service"
        echo "$TPL_SYSTEMCTL"
    elif [ "$sOpt" == "du" ]; then
        echoDebug INFO "Querying disk usages of {sinks,channels,logs}/*"
        runCmd du -hd2 $FLUME_DIR_CHANNELS \
        && runCmd du -ha $FLUME_DIR_SINKS \
        && runCmd du -ha $FLUME_DIR_LOGS
    elif [ "$sOpt" == "verify" ]; then
        sCsvDataDirs=$(echo $FLUME_DIR_CHANNELS/*/data | tr " " ",")
        echoDebug INFO "Verifying all channels' datadirs"
        runCmd exec $FLUME_DIR_BIN/flume-ng tool -c $FLUME_DIR_CONF FCINTEGRITYTOOL -l $sCsvDataDirs
    elif [ "$sOpt" == "housekeep" ]; then
        echoDebug INFO "Start housekeeping"
        if [ -z "$(which tmpwatch 2> /dev/null)" ]; then
            echoDebug ERROR "Tool 'tmpwatch' not found! Please 'yum install -y tmpwatch'"
            return 128
        fi
        runCmd tmpwatch -dumcvv $LIFECYCLE_FLUME_LOGS $FLUME_DIR_LOGS
        runCmd tmpwatch -dumcvv $LIFECYCLE_SINK_DISCARDS $FLUME_DIR_SINKS
    elif [ "$sOpt" == "test" ]; then
        echoDebug INFO "Showing test command"
        echo "$TPL_TEST"
    else
        echoDebug ERROR "invalid option '$sOpt'"
        echo "$HELP"
        return 1
    fi
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

main $@
